### ISSUE TITLE
pth model is saved as a directory

### ISSUE THREAD

**Issue by TheSunWillRise** [alibaba/FederatedScope#298]
I meet a bug when I run a hpo exp by
`python federatedscope/hpo.py --cfg federatedscope/example_configs/femnist/sha_wrap_fedex.yaml`

2022-08-08 14:42:38,910 (server:412)INFO: Server: Final evaluation is finished! Starting merging results.
Traceback (most recent call last):
  File "/home/chenganda.cad/codes/FederatedScope/federatedscope/hpo.py", line 43, in <module>
    _ = scheduler.optimize()
  File "/home/chenganda.cad/codes/FederatedScope/federatedscope/autotune/algos.py", line 254, in optimize
    current_perfs = self._iteration(current_configs)
  File "/home/chenganda.cad/codes/FederatedScope/federatedscope/autotune/algos.py", line 235, in _iteration
    perfs = self._evaluate(configs)
  File "/home/chenganda.cad/codes/FederatedScope/federatedscope/autotune/algos.py", line 183, in _evaluate
    perfs[i] = make_trial(trial_cfg)
  File "/home/chenganda.cad/codes/FederatedScope/federatedscope/autotune/algos.py", line 34, in make_trial
    results = Fed_runner.run()
  File "/home/chenganda.cad/codes/FederatedScope/federatedscope/core/fed_runner.py", line 192, in run
    self._run_simulation_online()
  File "/home/chenganda.cad/codes/FederatedScope/federatedscope/core/fed_runner.py", line 228, in _run_simulation_online
    self._handle_msg(msg)
  File "/home/chenganda.cad/codes/FederatedScope/federatedscope/core/fed_runner.py", line 420, in _handle_msg
    self.server.msg_handlers[msg.msg_type](msg)
  File "/home/chenganda.cad/codes/FederatedScope/federatedscope/core/worker/server.py", line 979, in callback_funcs_for_metrics
    return self.check_and_move_on(check_eval_result=True)
  File "/home/chenganda.cad/codes/FederatedScope/federatedscope/autotune/fedex/server.py", line 380, in check_and_move_on
    self.check_and_save()
  File "/home/chenganda.cad/codes/FederatedScope/federatedscope/autotune/fedex/server.py", line 415, in check_and_save
    self.save_best_results()
  File "/home/chenganda.cad/codes/FederatedScope/federatedscope/core/worker/server.py", line 505, in save_best_results
    self.aggregator.save_model(self._cfg.federate.save_to, self.state)
  File "/home/chenganda.cad/codes/FederatedScope/federatedscope/core/aggregator.py", line 58, in save_model
    torch.save(ckpt, path)
  File "/home/admin/chenganda.cad/anaconda3/envs/fs/lib/python3.9/site-packages/torch/serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/home/admin/chenganda.cad/anaconda3/envs/fs/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/admin/chenganda.cad/anaconda3/envs/fs/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: 'hpo/diff_False_eta0_-1.0_gamma_0.6626073361654039.pth'

The .pth model is saved as a directory.

**Comment by joneswong** [comment]
`hpo/` has to be created in advance. Then the checkpoints can be correctly saved to that folder in my execution:
![image](https://user-images.githubusercontent.com/6416895/183360074-3d2db2ad-e4d0-4475-aa7e-ad703c3d8cea.png)
