### ISSUE TITLE
Bug appears when run fedex with sha_wrap_fedex_arm.yaml

### ISSUE THREAD

**Issue by TheSunWillRise** [alibaba/FederatedScope#304]
Script
`python federatedscope/hpo.py --cfg federatedscope/example_configs/femnist/sha_wrap_fedex_arm.yaml`

Traceback (most recent call last):
  File "/home/chenganda.cad/codes/FederatedScope/federatedscope/hpo.py", line 42, in <module>
    scheduler = get_scheduler(init_cfg)
  File "/home/chenganda.cad/codes/FederatedScope/federatedscope/autotune/algos.py", line 81, in get_scheduler
    scheduler = SHAWrapFedex(init_cfg)
  File "/home/chenganda.cad/codes/FederatedScope/federatedscope/autotune/algos.py", line 98, in __init__
    self._init_configs = self._setup()
  File "/home/chenganda.cad/codes/FederatedScope/federatedscope/autotune/algos.py", line 392, in _setup
    self._search_space.add_hyperparameter(
  File "ConfigSpace/configuration_space.pyx", line 190, in ConfigSpace.configuration_space.ConfigurationSpace.add_hyperparameter
  File "ConfigSpace/configuration_space.pyx", line 201, in ConfigSpace.configuration_space.ConfigurationSpace._add_hyperparameter
ValueError: Hyperparameter 'hpo.table.idx' is already in the configuration space.

Besides, the parameter "cand" in sha_wrap_fedex_arm.yaml should be deleted.

**Comment by joneswong** [comment]
After this pr is merged, you could replace the third command @rayrayraykk  provides by `python federatedscope/hpo.py --cfg federatedscope/example_configs/femnist/avg/sha_wrap.yaml`
