### ISSUE TITLE
yacs error occurred when run command

### ISSUE THREAD

**Issue by data-alexpan** [alibaba/FederatedScope#321]
**Describe the bug**

when run command:  python federatedscope/main.py --cfg federatedscope/gfl/baseline/isolated_gin_minibatch_on_cikmcup.yaml --client_cfg federatedscope/gfl/baseline/isolated_gin_minibatch_on_cikmcup_per_client.yaml

**yacs error:**  AssertionError: `a` (cur type <class 'NoneType'>) must be an instance of <class 'yacs.config.CfgNode'>

**Desktop (please complete the following information):**
 - OS: [MACOS]
 - Version [13.0]

**Additional context**
2022-08-13 13:25:21,112 (fed_runner:302)INFO: Client 13 has been set up ... 
Traceback (most recent call last):
  File "/Users/panmin/Downloads/FederatedScope/federatedscope/main.py", line 46, in <module>
    runner = FedRunner(data=data,
  File "/Users/panmin/opt/anaconda3/envs/fs/lib/python3.9/site-packages/federatedscope-0.1.9-py3.9.egg/federatedscope/core/fed_runner.py", line 58, in __init__
    self._setup_for_standalone()
  File "/Users/panmin/opt/anaconda3/envs/fs/lib/python3.9/site-packages/federatedscope-0.1.9-py3.9.egg/federatedscope/core/fed_runner.py", line 115, in _setup_for_standalone
    self.client[client_id] = self._setup_client(
  File "/Users/panmin/opt/anaconda3/envs/fs/lib/python3.9/site-packages/federatedscope-0.1.9-py3.9.egg/federatedscope/core/fed_runner.py", line 278, in _setup_client
    client_specific_config.merge_from_other_cfg(
  File "/Users/panmin/opt/anaconda3/envs/fs/lib/python3.9/site-packages/federatedscope-0.1.9-py3.9.egg/federatedscope/core/configs/config.py", line 153, in merge_from_other_cfg
    merge_dict_a_into_b(cfg_other, self, self, [])
  File "/Users/panmin/opt/anaconda3/envs/fs/lib/python3.9/site-packages/federatedscope-0.1.9-py3.9.egg/federatedscope/core/configs/config.py", line 70, in merge_dict_a_into_b
    _assert_with_logging(
  File "/Users/panmin/opt/anaconda3/envs/fs/lib/python3.9/site-packages/yacs-0.1.8-py3.9.egg/yacs/config.py", line 545, in _assert_with_logging
    assert cond, msg
AssertionError: `a` (cur type <class 'NoneType'>) must be an instance of <class 'yacs.config.CfgNode'>

**Comment by xieyxclack** [comment]
May I ask that which branch you run the command? master or cikm22competition?

**Comment by qiudi0127** [comment]
Cikm22competition will meet this error.

**Comment by qiudi0127** [comment]
@xieyxclack Cikm22competition will meet this error.

**Comment by xieyxclack** [comment]
> @xieyxclack Cikm22competition will meet this error.

With the experience of @data-alexpan , you might need to install the environment  according to [link](https://tianchi.aliyun.com/forum/postDetail?spm=5176.12586969.0.0.47943ab4aHybHr&postId=402279)

**Comment by data-alexpan** [comment]
thanks buddy. It's worked.
