### ISSUE TITLE
Is there script/config file example for FL training on celeba, toy and nlp task?

### ISSUE THREAD

**Issue by zyzhang1130** [alibaba/FederatedScope#445]
**Is your feature request related to a problem? Please describe.**
I am having trouble modifying the example to train on celeba, toy data for vision tasks as well as modifying the existing script (01_quick_start.py) to run nlp tasks. 

**Describe the solution you'd like**
Is there a script/config file that I can follow? A simple one for vanilla fedavg will do.

**Describe alternatives you've considered**
simply change `cfg.data.type = 'femnist'` to `cfg.data.type = 'celeba'`, ``cfg.data.type = 'CIFAR10@torchvision'`` or `cfg.data.type = 'toy'` will cause error. It is not clear to me which part of the script I should modify to run nlp tasks.

error when set `cfg.data.type = 'celeba'`:
```
Traceback (most recent call last):
  File "C:\Users\Zhang Ze Yu\OneDrive - National University of Singapore\Documents\GitHub\FederatedScope\01_quick_start.py", line 36, in <module>
    data, modified_cfg = get_data(cfg.clone())
  File "C:\Users\Zhang Ze Yu\OneDrive - National University of Singapore\Documents\GitHub\FederatedScope\federatedscope\core\auxiliaries\data_builder.py", line 629, in get_data
    data, modified_config = load_cv_dataset(config)
  File "C:\Users\Zhang Ze Yu\OneDrive - National University of Singapore\Documents\GitHub\FederatedScope\federatedscope\cv\dataloader\dataloader.py", line 25, in load_cv_dataset
    dataset = LEAF_CV(root=path,
  File "C:\Users\Zhang Ze Yu\OneDrive - National University of Singapore\Documents\GitHub\FederatedScope\federatedscope\cv\dataset\leaf_cv.py", line 54, in __init__
    super(LEAF_CV, self).__init__(root, name, transform, target_transform)
  File "C:\Users\Zhang Ze Yu\OneDrive - National University of Singapore\Documents\GitHub\FederatedScope\federatedscope\cv\dataset\leaf.py", line 38, in __init__
    self.process_file()
  File "C:\Users\Zhang Ze Yu\OneDrive - National University of Singapore\Documents\GitHub\FederatedScope\federatedscope\cv\dataset\leaf.py", line 85, in process_file
    self.extract()
  File "C:\Users\Zhang Ze Yu\OneDrive - National University of Singapore\Documents\GitHub\FederatedScope\federatedscope\cv\dataset\leaf.py", line 76, in extract
    with zipfile.ZipFile(osp.join(self.raw_dir, name), 'r') as f:
  File "C:\Users\Zhang Ze Yu\anaconda3\lib\zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "C:\Users\Zhang Ze Yu\anaconda3\lib\zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
error when set `cfg.data.type = 'CIFAR10@torchvision'`:
```
Files already downloaded and verified
Files already downloaded and verified
2022-12-02 01:24:58,821 (splitter_builder:43)WARNING: Splitter  not found.
Traceback (most recent call last):
  File "C:\Users\Zhang Ze Yu\OneDrive - National University of Singapore\Documents\GitHub\FederatedScope\01_quick_start.py", line 36, in <module>
    data, modified_cfg = get_data(cfg.clone())
  File "C:\Users\Zhang Ze Yu\OneDrive - National University of Singapore\Documents\GitHub\FederatedScope\federatedscope\core\auxiliaries\data_builder.py", line 661, in get_data
    data, modified_config = load_external_data(config)
  File "C:\Users\Zhang Ze Yu\OneDrive - National University of Singapore\Documents\GitHub\FederatedScope\federatedscope\core\auxiliaries\data_builder.py", line 583, in load_external_data
    splitter(dataset[split], prior=train_label_distribution)):
TypeError: 'NoneType' object is not callable
```

**Comment by xieyxclack** [comment]
Many thanks for your interest!
An example configuration is provided in https://github.com/alibaba/FederatedScope/blob/master/federatedscope/cv/baseline/fedavg_convnet2_on_celeba.yaml

BTW, it seems that there might be some errors in the downloaded file of celeba dataset according the provided logs, maybe you can remove it, and re-download the dataset via (i) automatically downloading when you run the above configuration; (2) manually downloading from https://federatedscope.oss-cn-beijing.aliyuncs.com/celeba_all_data.zip and putting the zip file to `FederatedScope/data/celeba/raw/`

Hope this helps!

**Comment by zyzhang1130** [comment]
> 

Thank you for the prompt reply. I am currently trying to download the celeba dataset directly from the weblink. By the way I also found the script for nlp tasks. Might reopen the issue if there is any further related questions.

**Comment by zyzhang1130** [comment]
I am having the following error with `pytorch=1.10.1` and  `torchtext=0.11.1`:
```
Traceback (most recent call last):
  File "/home/zhan1130/FederatedScope/01_quick_start.py", line 36, in <module>
    data, modified_cfg = get_data(cfg.clone())
  File "/home/zhan1130/FederatedScope/federatedscope/core/auxiliaries/data_builder.py", line 634, in get_data
    data, modified_config = load_nlp_dataset(config)
  File "/home/zhan1130/FederatedScope/federatedscope/nlp/dataloader/dataloader.py", line 24, in load_nlp_dataset
    transforms_funcs = get_transform(config, 'torchtext')
  File "/home/zhan1130/FederatedScope/federatedscope/core/auxiliaries/transform_builder.py", line 27, in get_transform
    transforms = getattr(import_module(package), 'transforms')
AttributeError: module 'torchtext' has no attribute 'transforms'
```
I didn't manage to find related issues online. The versions of torch and torchtext are as specified in [README.md](https://github.com/alibaba/FederatedScope#readme)

**Comment by xieyxclack** [comment]
Could you please provide the configuration to reproduce the error? It seems that the error is caused by using `transforms`, a preprocess method designed for torchvision, in torchtext. 
For example for running FS for NLP applications, please refer to https://github.com/alibaba/FederatedScope/tree/master/federatedscope/nlp/baseline for examples.

Thanks again for your interest!

**Comment by zyzhang1130** [comment]
@rayrayraykk Thanks a lot for the clarification!
