### ISSUE TITLE
report cuda error when trying to launch up the demo case

### ISSUE THREAD

**Issue by lmaxeniro** [alibaba/FederatedScope#89]
Hi when I am trying to  launch up the demo case, cuda relevant error was reported as below:

I am using conda to manage the environment. in other env I have the pytorch works on cuda without any problem.
I think this could be the installation issue-- I did not install anything by myself, totally following your guidance.
My cuda version:
NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6    
and my torch version: 1.10.1

 ```
(fedscope) liangma@lMa-X1:~/prj/FederatedScope$ python federatedscope/main.py --cfg federatedscope/example_configs/femnist.yaml

...
2022-05-13 22:06:09,249 (server:520) INFO: ----------- Starting training (Round #0) -------------
Traceback (most recent call last):
  File "/home/liangma/prj/FederatedScope/federatedscope/main.py", line 41, in <module>
    _ = runner.run()
  File "/home/liangma/miniconda3/envs/fedscope/lib/python3.9/site-packages/federatedscope-0.1.0-py3.9.egg/federatedscope/core/fed_runner.py", line 136, in run
    self._handle_msg(msg)
  File "/home/liangma/miniconda3/envs/fedscope/lib/python3.9/site-packages/federatedscope-0.1.0-py3.9.egg/federatedscope/core/fed_runner.py", line 254, in _handle_msg
    self.client[each_receiver].msg_handlers[msg.msg_type](msg)
  File "/home/liangma/miniconda3/envs/fedscope/lib/python3.9/site-packages/federatedscope-0.1.0-py3.9.egg/federatedscope/core/worker/client.py", line 202, in callback_funcs_for_model_para
    sample_size, model_para_all, results = self.trainer.train()
  File "/home/liangma/miniconda3/envs/fedscope/lib/python3.9/site-packages/federatedscope-0.1.0-py3.9.egg/federatedscope/core/trainers/trainer.py", line 374, in train
    self._run_routine("train", hooks_set, target_data_split_name)
  File "/home/liangma/miniconda3/envs/fedscope/lib/python3.9/site-packages/federatedscope-0.1.0-py3.9.egg/federatedscope/core/trainers/trainer.py", line 208, in _run_routine
    hook(self.ctx)
  File "/home/liangma/miniconda3/envs/fedscope/lib/python3.9/site-packages/federatedscope-0.1.0-py3.9.egg/federatedscope/core/trainers/trainer.py", line 474, in _hook_on_fit_start_init
    ctx.model.to(ctx.device)
  File "/home/liangma/miniconda3/envs/fedscope/lib/python3.9/site-packages/torch/nn/modules/module.py", line 899, in to
    return self._apply(convert)
  File "/home/liangma/miniconda3/envs/fedscope/lib/python3.9/site-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/home/liangma/miniconda3/envs/fedscope/lib/python3.9/site-packages/torch/nn/modules/module.py", line 593, in _apply
    param_applied = fn(param)
  File "/home/liangma/miniconda3/envs/fedscope/lib/python3.9/site-packages/torch/nn/modules/module.py", line 897, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/liangma/miniconda3/envs/fedscope/lib/python3.9/site-packages/torch/cuda/__init__.py", line 208, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

```

**Comment by yxdyc** [comment]
Thanks for your attention!
The problem ``Torch not compiled with CUDA enabled`` occurs when the cuda and torch versions mismatch. To fix it, you may need to re-set the conda env and install torch from a version-fixed wheel (see similar solutions [here](https://github.com/pytorch/pytorch/issues/30664#issuecomment-1055418982)). Any other suggestions @rayrayraykk ?

**Comment by rayrayraykk** [comment]
It looks like it is caused by not installing pytorch correctly.

Here are 2 possible solutions:
1. Downgrade your CUDA version to 11.3.
2. Install pytorch manually via `pip install torch --pre --extra-index-url https://download.pytorch.org/whl/nightly/cu116`. For more details, see: https://discuss.pytorch.org/t/pytorch-cuda-11-6/149647.

**Comment by yxdyc** [comment]
> Hi, Thanks for the reply.
> 
> I don't want to change my CUDA version as this is OK for my other project.. So I simply reinstall the torch, as reported as below it is success:
> 
> ```
> pip install torch --pre --extra-index-url https://download.pytorch.org/whl/nightly/cu116
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://download.pytorch.org/whl/nightly/cu116
> Requirement already satisfied: torch in /home/liangma/miniconda3/envs/fedscope/lib/python3.9/site-packages (1.11.0)
> Requirement already satisfied: typing-extensions in /home/liangma/miniconda3/envs/fedscope/lib/python3.9/site-packages (from torch) (4.2.0)
> ```
> 
> My torch version is 1.11.0 now but I still get the same error report when running the demo project.
> 
> When I checked the torch version-- I find that what is installed are pytorch (which is from the requirement.txt) but not torch, and my pytorch is likely "cpu_only". Does that explain the why problem happen?
> 
> ```
> $ conda list | grep torch:
> cpuonly                   2.0                           0    pytorch
> ffmpeg                    4.3                  hf484d3e_0    pytorch
> pyg                       2.0.4           py39_torch_1.10.0_cpu    pyg
> pytorch                   1.10.1              py3.9_cpu_0    pytorch
> pytorch-cluster           1.6.0           py39_torch_1.10.0_cpu    pyg
> pytorch-mutex             1.0                         cpu    pytorch
> pytorch-scatter           2.0.9           py39_torch_1.10.0_cpu    pyg
> pytorch-sparse            0.6.13          py39_torch_1.10.0_cpu    pyg
> pytorch-spline-conv       1.2.1           py39_torch_1.10.0_cpu    pyg
> torch                     1.11.0                   pypi_0    pypi
> torchaudio                0.10.1                 py39_cpu  [cpuonly]  pytorch
> torchtext                 0.11.1                     py39    pytorch
> torchvision               0.11.2                 py39_cpu  [cpuonly]  pytorch
> ```

It seems that you faced the problem with cpu-version as [others met](https://github.com/pytorch/pytorch/issues/30664#issuecomment-956655944).  You can try this [solution](https://github.com/pytorch/pytorch/issues/30664#issuecomment-757431613) to re-install torch.

**Comment by lmaxeniro** [comment]
OK, I had completely removed my conda env and re-install for fedscope--this time I get the cudatoolkit 11.3.1 installed. then the demo project can be run up without problem.

**Comment by lmaxeniro** [comment]
OK, I had completely removed my conda env and re-install for fedscope--this time I get the cudatoolkit 11.3.1 installed. then the demo project can be run up without problem.
